name: C/C++ CI

on: workflow_dispatch
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: g++ -o OSRECinterp.bin OSREC-interp.cpp tinyfiledialogs.c
    
